name: Go Code Format Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run gofmt to check code formatting
        run: |
          gofmt -l .
        continue-on-error: true

      - name: Fail if formatting issues found
        run: |
          FORMATTED=$(gofmt -l .)
          if [ -n "$FORMATTED" ]; then
            echo "The following files need to be formatted:"
            echo "$FORMATTED"
            exit 1
          fi
